# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APShopping' do
use_frameworks!
pod 'ws'
pod 'Arrow'

  target 'APShoppingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APShoppingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
